version: '3.5'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: agoodpwd
      MYSQL_DATABASE: mydb

    volumes:
      - mysql-data:/var/lib/mysql

  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 9999:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: agoodpwd
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - db

volumes:
  mysql-data:
  wordpress-data:
