version: '3'
services:
  proxy:
    image: nginx
    container_name: proxyserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    build:
      ../ex1_5/App/Dockerfile
    container_name: nodesfrontend_25
    image: nodes
    command: npm start
    ports:
      - 5000
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      - backend

  redis:
    image: redis
    container_name: cache_25
    expose:
      - 6379

  db:
    image: postgres
    restart: unless-stopped
    container_name: db_25
    environment:
      POSTGRES_USER: usernamedm
      POSRTGRES_PASSWORD: usernamedm
      POSTGRES_DB: dmdb

  backend:
    build:
      ../ex1_6/App/Dockerfile
    container_name: nodesbackend_25
    depends_on:
      - db
      - redis
    image: nodesback
    command: npm start
    ports:
      - 8000
    volumes:
      - ../ex1_6/logs.txt:/App/logs.txt
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=usernamedm
      - DB_PASSWORD=usernamedm
      - DB_NAME=dmdb
      - DB_HOST=localhost
